let sourceToyList = [
  {
    priceInUAH: 120,
    ageGroup: "9",
    color: "red",
    size: "small",
    doorCount: "2",
    lengthInMM: "150",
    material: "steel",
    image: "images/rc-car-origin.svg",
  },
  {
    priceInUAH: 300,
    ageGroup: "9",
    color: "red",
    size: "medium",
    doorCount: "2",
    lengthInMM: "150",
    material: "steel",
    image: "images/rc-car-origin.svg",
  },
  {
    priceInUAH: 170,
    ageGroup: "9",
    color: "Blue",
    size: "small",
    doorCount: "4",
    lengthInMM: "120",
    material: "steel",
    image: "images/rc-car.svg",
  },
  {
    priceInUAH: 100,
    ageGroup: "6",
    color: "Blue",
    size: "small",
    doorCount: "2",
    lengthInMM: "80",
    material: "steel",
    image: "images/rc-car.svg",
  },
  {
    priceInUAH: 500,
    ageGroup: "9",
    color: "Blue",
    size: "medium",
    doorCount: "4",
    lengthInMM: "350",
    material: "steel",
    image: "images/rc-car.svg",
  },
  {
    priceInUAH: 85,
    ageGroup: "6",
    color: "red",
    size: "small",
    doorCount: "2",
    lengthInMM: "50",
    material: "steel",
    image: "images/rc-car-origin.svg",
  },
  {
    priceInUAH: 2000,
    ageGroup: "9",
    color: "Blue",
    size: "lerge",
    doorCount: "4",
    lengthInMM: "1600",
    material: "steel",
    image: "images/rc-car.svg",
  },
  {
    priceInUAH: 90,
    ageGroup: "3",
    color: "red",
    size: "small",
    doorCount: "4",
    lengthInMM: "70",
    material: "steel",
    image: "images/rc-car-origin.svg",
  },
  {
    priceInUAH: 450,
    ageGroup: "12",
    color: "Blue",
    size: "large",
    doorCount: "4",
    lengthInMM: "300",
    material: "steel",
    image: "images/rc-car.svg",
  },
];

if (
  localStorage.getItem("SourceToyList") == null ||
  JSON.parse(localStorage.getItem("SourceToyList")).length == 0
) {
  localStorage.setItem("SourceToyList", JSON.stringify(sourceToyList));
}
